openapi: 3.0.3
info:
  title: Web IDE
  description: Web IDE
  version: 1.0.1
servers:
  - url: 'http://localhost:8080'
paths:
  /api/v1/auth/email:
    $ref: './auth/email.yaml'
  /api/v1/auth/email/check:
    $ref: './auth/emailCheck.yaml'
  /api/v1/auth/signin:
    $ref: './auth/signin.yaml'
  /api/v1/auth/signin/kakao:
    $ref: './auth/kakaoSignin.yaml'
  /api/v1/auth/signup:
    $ref: './auth/signup.yaml'
  /api/v1/auth/password/reset/email:
    $ref: './auth/passwordReset.yaml'
  /api/v1/auth/password/reset/check:
    $ref: './auth/passwordResetCheck.yaml'
  /api/v1/problems:
    $ref: './problem/problems.yaml'
  /api/v1/problems/{id}:
    $ref: './problem/problem.yaml'
  /api/v1/problems/{id}/code/test:
    $ref: './code/test.yaml'
  /api/v1/problems/{id}/code/submit:
    $ref: './code/submit.yaml'
