openapi: 3.0.3
info:
  title: Web IDE
  description: Web IDE
  version: 1.0.1
servers:
  - url: 'http://localhost:8080'
paths:
  /api/v1/auth/email:
    $ref: './auth/email.yaml'
  /api/v1/auth/email/check:
    $ref: './auth/emailCheck.yaml'
  /api/v1/auth/signin:
    $ref: './auth/signin.yaml'
  /api/v1/auth/signin/kakao:
    $ref: './auth/kakaoSignin.yaml'
  /api/v1/auth/signup:
    $ref: './auth/signup.yaml'
  /api/v1/auth/password/reset/email:
    $ref: './auth/passwordReset.yaml'
  /api/v1/auth/password/reset/check:
    $ref: './auth/passwordResetCheck.yaml'
  /api/v1/problems:
    $ref: './problem/problems.yaml'
  /api/v1/problems/{id}:
    $ref: './problem/problem.yaml'
  /api/v1/problems/{id}/code/test:
    $ref: './code/test.yaml'
  /api/v1/problems/{id}/code/submit:
    $ref: './code/submit.yaml'
  /api/v1/problems/{id}/solutions:
    $ref: './solution/solutions.yaml'
  /api/v1/problems/{problemId}/solutions/{solutionId}:
    $ref: './solution/solution.yaml'
  /api/v1/problems/{problemId}/solutions/{solutionId}/like:
    $ref: './solution/like.yaml'
  /api/v1/solutions/{solutionId}/comments:
    $ref: './comment/comments.yaml'
  /api/v1/solutions/{solutionId}/comments/{commentId}:
    $ref: './comment/comment.yaml'
  /api/v1/solutions/{solutionId}/comments/{commentId}/like:
    $ref: './comment/like.yaml'
  /api/v1/comments/{commentId}/replies:
    $ref: './reply/replies.yaml'
  /api/v1/comments/{commentId}/replies/{replyId}:
    $ref: './reply/reply.yaml'
  /api/v1/comments/{commentId}/replies/{replyId}/like:
    $ref: './reply/like.yaml'
  /api/v1/problems/{id}/quizzes:
    $ref: './quiz/quizzes.yaml'
  /api/v1/problems/{id}/answers:
    $ref: './coach/answers.yaml'
